/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://jpb6j3qg25eg3gckecqri5vigq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6rg2c7oke5arlal7mjcg4vfl24",
    "aws_cognito_identity_pool_id": "eu-west-2:a6a9392e-985e-4532-ab53-d6cc854cb966",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_2yE2TlfZs",
    "aws_user_pools_web_client_id": "2m7h9hianbp1nsnvl2lpfbo9iu",
    "oauth": {}
};


export default awsmobile;
